### PR TITLE
Fix deprecations regarding Computed Property Overrides

### LINKED ISSUE #1908: Deprecation warnings on Ember 3.9 (computed property was just overriden)
As mentioned in issue https://github.com/simplabs/ember-simple-auth/issues/1799, there is stil one deprecation warning with Ember 3.9:

`DEPRECATION: The <(unknown):ember242>#_isFastBoot computed property was just overriden. This removes the computed property and replaces it with a plain value, and has been deprecated. If you want this behavior, consider defining a setter which does it manually.`

The stacktrace is referencing the following line

https://github.com/simplabs/ember-simple-auth/blob/76e0eacf94f1d1d4d1194b3ef93ceae0bc5e000e/addon/session-stores/adaptive.js#L130

### PR DESCRIPTION
**Pull request by marcoow**
This fixes the deprecations regarding overridden computed properties. Most of these CPs were only used in testing and should be properly mocked via the container anyway (e.g. `_fastBoot`).

### TODO

- [x] all deprecations in app code should be fixed but there are some left in the testing code (mainly the code around testing adaptive and cookie session stores which is relatively messy anyway 😞) - that should be fixed before releasing this as well.

closes #1908
closes #2044 
closes #1938

### CODE REVIEW

File: addon/internal-session.js [hunk 1]
```diff
@@ -192,7 +192,10 @@ export default ObjectProxy.extend(Evented, {
     });
   },
 
-  _lookupAuthenticator(authenticator) {
-    return getOwner(this).lookup(authenticator);
+  _lookupAuthenticator(authenticatorName) {
+    let owner = getOwner(this);
+    let authenticator = getOwner(this).lookup(authenticatorName);
```
Comment (sdebarros) [inline addon/internal-session.js]:
```suggestion
    let authenticator = owner.lookup(authenticatorName);
```

**Comment by pjcarly** [comment]
Great, thanks for the merge.

Could we get a new NPM release?
