### PR TITLE
fix tests

### LINKED ISSUE #1472: Fix Build
The build is failing since this commit https://travis-ci.org/simplabs/ember-simple-auth/builds/298626798 which is likely unrelated to the failures though 😞

### PR DESCRIPTION
**Pull request by marcoow**
Since we're ignoring the `yarn.lock` file on Travis we get the new and fixed ember-try version there that changes our test runs so that they actually run against early versions of ember and ember-data which did lead to errors (as the scenarios generated automatically by ember-try don't include correct versions for ember-cli-shims and ember-data which broke our tests).

The only fix for now sadly is to go back to explicit ember-try scenarios…

closes #1472

### CODE REVIEW

File: config/ember-try.js [hunk 1]
```diff
@@ -1,5 +1,189 @@
...
+      name: 'default',
+      dependencies: { }
+    },
+    {
+      name: 'ember-1.12',
+      bower: {
+        dependencies: {
+          ember: '~1.12.0',
+          'ember-cli-shims': '0.0.6',
+          'ember-data': '~1.13.0',
```
Comment (Turbo87) [inline config/ember-try.js]: shouldn't this use Ember Data 1.12 too?

File: package.json [hunk 2]
```diff
@@ -39,6 +39,7 @@
   "devDependencies": {
     "body-parser": "^1.17.2",
     "bootstrap": "^3.3.7",
+    "bower": "^1.8.2",
```
Comment (Turbo87) [inline package.json]: this shouldn't be needed anymore, https://github.com/ember-cli/ember-try/issues/161 got fixed tonight.

File: config/ember-try.js (hunk 1 above)
Comment (marcoow) [reply config/ember-try.js]: Ember Data 1.12 doesn't seem to exist…

File: package.json (hunk 2 above)
Comment (marcoow) [reply package.json]: 👍

File: config/ember-try.js (hunk 1 above)
Comment (Turbo87) [reply config/ember-try.js]: ah, indeed. according to https://github.com/emberjs/data/tags?after=v1.13.3 there was only v1.0.0 betas before the v1.13.0 release 🤔

Comment (marcoow) [reply config/ember-try.js]: The Ember Data version doesn't really matter much for the ESA tests though. In fact it's only needed so that the current user can be fetched during an acceptance test where the fetching itself doesn't really relate to ESA at all.

Comment (marcoow) [reply config/ember-try.js]: > there was only v1.0.0 betas before the v1.13.0 release 🤔

Those were the wild and crazy days, in particular with Ember Data after all 😜
